// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	EngineSignatureScopes      = "EngineSignature.Scopes"
	EngineSignatureInputScopes = "EngineSignatureInput.Scopes"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Message string `json:"message" yaml:"message"`
}

// ContentDigest defines model for ContentDigest.
type ContentDigest = string

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = openapi_types.UUID

// EngineForbidden defines model for EngineForbidden.
type EngineForbidden = ErrorResponse

// EngineUnauthorized defines model for EngineUnauthorized.
type EngineUnauthorized = ErrorResponse

// PostEngineTelemetryLogParams defines parameters for PostEngineTelemetryLog.
type PostEngineTelemetryLogParams struct {
	// ContentDigest RFC 9530 SHA-256 digest of the transmitted request content.
	ContentDigest ContentDigest `json:"Content-Digest" yaml:"Content-Digest"`

	// IdempotencyKey Stable UUID reused for retries of the same mutation or ingestion request.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key" yaml:"Idempotency-Key"`
}

// PostEngineTelemetryTracesParams defines parameters for PostEngineTelemetryTraces.
type PostEngineTelemetryTracesParams struct {
	// ContentDigest RFC 9530 SHA-256 digest of the transmitted request content.
	ContentDigest ContentDigest `json:"Content-Digest" yaml:"Content-Digest"`

	// IdempotencyKey Stable UUID reused for retries of the same mutation or ingestion request.
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key" yaml:"Idempotency-Key"`
}

// PostEngineTelemetryLogJSONRequestBody defines body for PostEngineTelemetryLog for application/json ContentType.
type PostEngineTelemetryLogJSONRequestBody = Log

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /engines/config)
	GetEngineConfig(w http.ResponseWriter, r *http.Request)

	// (GET /engines/telemetry/log)
	GetEngineTelemetryLog(w http.ResponseWriter, r *http.Request)

	// (POST /engines/telemetry/log)
	PostEngineTelemetryLog(w http.ResponseWriter, r *http.Request, params PostEngineTelemetryLogParams)

	// (GET /engines/telemetry/traces)
	GetEngineTelemetryTraces(w http.ResponseWriter, r *http.Request)

	// (POST /engines/telemetry/traces)
	PostEngineTelemetryTraces(w http.ResponseWriter, r *http.Request, params PostEngineTelemetryTracesParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /engines/config)
func (_ Unimplemented) GetEngineConfig(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /engines/telemetry/log)
func (_ Unimplemented) GetEngineTelemetryLog(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /engines/telemetry/log)
func (_ Unimplemented) PostEngineTelemetryLog(w http.ResponseWriter, r *http.Request, params PostEngineTelemetryLogParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /engines/telemetry/traces)
func (_ Unimplemented) GetEngineTelemetryTraces(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /engines/telemetry/traces)
func (_ Unimplemented) PostEngineTelemetryTraces(w http.ResponseWriter, r *http.Request, params PostEngineTelemetryTracesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetEngineConfig operation middleware
func (siw *ServerInterfaceWrapper) GetEngineConfig(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, EngineSignatureScopes, []string{})

	ctx = context.WithValue(ctx, EngineSignatureInputScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEngineConfig(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEngineTelemetryLog operation middleware
func (siw *ServerInterfaceWrapper) GetEngineTelemetryLog(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, EngineSignatureScopes, []string{})

	ctx = context.WithValue(ctx, EngineSignatureInputScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEngineTelemetryLog(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEngineTelemetryLog operation middleware
func (siw *ServerInterfaceWrapper) PostEngineTelemetryLog(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, EngineSignatureScopes, []string{})

	ctx = context.WithValue(ctx, EngineSignatureInputScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostEngineTelemetryLogParams

	headers := r.Header

	// ------------- Required header parameter "Content-Digest" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Content-Digest")]; found {
		var ContentDigest ContentDigest
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Content-Digest", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Content-Digest", valueList[0], &ContentDigest, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Content-Digest", Err: err})
			return
		}

		params.ContentDigest = ContentDigest

	} else {
		err := fmt.Errorf("Header parameter Content-Digest is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Content-Digest", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEngineTelemetryLog(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetEngineTelemetryTraces operation middleware
func (siw *ServerInterfaceWrapper) GetEngineTelemetryTraces(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, EngineSignatureScopes, []string{})

	ctx = context.WithValue(ctx, EngineSignatureInputScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetEngineTelemetryTraces(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostEngineTelemetryTraces operation middleware
func (siw *ServerInterfaceWrapper) PostEngineTelemetryTraces(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, EngineSignatureScopes, []string{})

	ctx = context.WithValue(ctx, EngineSignatureInputScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params PostEngineTelemetryTracesParams

	headers := r.Header

	// ------------- Required header parameter "Content-Digest" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Content-Digest")]; found {
		var ContentDigest ContentDigest
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Content-Digest", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Content-Digest", valueList[0], &ContentDigest, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Content-Digest", Err: err})
			return
		}

		params.ContentDigest = ContentDigest

	} else {
		err := fmt.Errorf("Header parameter Content-Digest is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Content-Digest", Err: err})
		return
	}

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostEngineTelemetryTraces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/engines/config", wrapper.GetEngineConfig)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/engines/telemetry/log", wrapper.GetEngineTelemetryLog)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/engines/telemetry/log", wrapper.PostEngineTelemetryLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/engines/telemetry/traces", wrapper.GetEngineTelemetryTraces)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/engines/telemetry/traces", wrapper.PostEngineTelemetryTraces)
	})

	return r
}

type EngineForbiddenJSONResponse ErrorResponse

type EngineUnauthorizedResponseHeaders struct {
	Date string
}
type EngineUnauthorizedJSONResponse struct {
	Body ErrorResponse

	Headers EngineUnauthorizedResponseHeaders
}

type GetEngineConfigRequestObject struct {
}

type GetEngineConfigResponseObject interface {
	VisitGetEngineConfigResponse(w http.ResponseWriter) error
}

type GetEngineConfig200JSONResponse Config

func (response GetEngineConfig200JSONResponse) VisitGetEngineConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineConfig400JSONResponse struct {
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

func (response GetEngineConfig400JSONResponse) VisitGetEngineConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineConfig401JSONResponse struct{ EngineUnauthorizedJSONResponse }

func (response GetEngineConfig401JSONResponse) VisitGetEngineConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Date", fmt.Sprint(response.Headers.Date))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetEngineConfig403JSONResponse struct{ EngineForbiddenJSONResponse }

func (response GetEngineConfig403JSONResponse) VisitGetEngineConfigResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineConfig404Response struct {
}

func (response GetEngineConfig404Response) VisitGetEngineConfigResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type GetEngineTelemetryLogRequestObject struct {
}

type GetEngineTelemetryLogResponseObject interface {
	VisitGetEngineTelemetryLogResponse(w http.ResponseWriter) error
}

type GetEngineTelemetryLog200JSONResponse struct {
	Log *string `json:"log,omitempty" yaml:"log,omitempty"`
}

func (response GetEngineTelemetryLog200JSONResponse) VisitGetEngineTelemetryLogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineTelemetryLog400JSONResponse struct {
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

func (response GetEngineTelemetryLog400JSONResponse) VisitGetEngineTelemetryLogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineTelemetryLog401JSONResponse struct{ EngineUnauthorizedJSONResponse }

func (response GetEngineTelemetryLog401JSONResponse) VisitGetEngineTelemetryLogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Date", fmt.Sprint(response.Headers.Date))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetEngineTelemetryLog403JSONResponse struct{ EngineForbiddenJSONResponse }

func (response GetEngineTelemetryLog403JSONResponse) VisitGetEngineTelemetryLogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineTelemetryLog404Response struct {
}

func (response GetEngineTelemetryLog404Response) VisitGetEngineTelemetryLogResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostEngineTelemetryLogRequestObject struct {
	Params PostEngineTelemetryLogParams
	Body   *PostEngineTelemetryLogJSONRequestBody
}

type PostEngineTelemetryLogResponseObject interface {
	VisitPostEngineTelemetryLogResponse(w http.ResponseWriter) error
}

type PostEngineTelemetryLog201Response struct {
}

func (response PostEngineTelemetryLog201Response) VisitPostEngineTelemetryLogResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PostEngineTelemetryLog400JSONResponse struct {
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

func (response PostEngineTelemetryLog400JSONResponse) VisitPostEngineTelemetryLogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostEngineTelemetryLog401JSONResponse struct{ EngineUnauthorizedJSONResponse }

func (response PostEngineTelemetryLog401JSONResponse) VisitPostEngineTelemetryLogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Date", fmt.Sprint(response.Headers.Date))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostEngineTelemetryLog403JSONResponse struct{ EngineForbiddenJSONResponse }

func (response PostEngineTelemetryLog403JSONResponse) VisitPostEngineTelemetryLogResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineTelemetryTracesRequestObject struct {
}

type GetEngineTelemetryTracesResponseObject interface {
	VisitGetEngineTelemetryTracesResponse(w http.ResponseWriter) error
}

type GetEngineTelemetryTraces200JSONResponse struct {
	Trace *string `json:"trace,omitempty" yaml:"trace,omitempty"`
}

func (response GetEngineTelemetryTraces200JSONResponse) VisitGetEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineTelemetryTraces400JSONResponse struct {
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

func (response GetEngineTelemetryTraces400JSONResponse) VisitGetEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineTelemetryTraces401JSONResponse struct{ EngineUnauthorizedJSONResponse }

func (response GetEngineTelemetryTraces401JSONResponse) VisitGetEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Date", fmt.Sprint(response.Headers.Date))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetEngineTelemetryTraces403JSONResponse struct{ EngineForbiddenJSONResponse }

func (response GetEngineTelemetryTraces403JSONResponse) VisitGetEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetEngineTelemetryTraces404Response struct {
}

func (response GetEngineTelemetryTraces404Response) VisitGetEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PostEngineTelemetryTracesRequestObject struct {
	Params PostEngineTelemetryTracesParams
	Body   io.Reader
}

type PostEngineTelemetryTracesResponseObject interface {
	VisitPostEngineTelemetryTracesResponse(w http.ResponseWriter) error
}

type PostEngineTelemetryTraces200ApplicationXProtobufResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response PostEngineTelemetryTraces200ApplicationXProtobufResponse) VisitPostEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/x-protobuf")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type PostEngineTelemetryTraces400JSONResponse struct {
	Message *string `json:"message,omitempty" yaml:"message,omitempty"`
}

func (response PostEngineTelemetryTraces400JSONResponse) VisitPostEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type PostEngineTelemetryTraces401JSONResponse struct{ EngineUnauthorizedJSONResponse }

func (response PostEngineTelemetryTraces401JSONResponse) VisitPostEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Date", fmt.Sprint(response.Headers.Date))
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostEngineTelemetryTraces403JSONResponse struct{ EngineForbiddenJSONResponse }

func (response PostEngineTelemetryTraces403JSONResponse) VisitPostEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type PostEngineTelemetryTraces429ResponseHeaders struct {
	RetryAfter string
}

type PostEngineTelemetryTraces429Response struct {
	Headers PostEngineTelemetryTraces429ResponseHeaders
}

func (response PostEngineTelemetryTraces429Response) VisitPostEngineTelemetryTracesResponse(w http.ResponseWriter) error {
	w.Header().Set("Retry-After", fmt.Sprint(response.Headers.RetryAfter))
	w.WriteHeader(429)
	return nil
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /engines/config)
	GetEngineConfig(ctx context.Context, request GetEngineConfigRequestObject) (GetEngineConfigResponseObject, error)

	// (GET /engines/telemetry/log)
	GetEngineTelemetryLog(ctx context.Context, request GetEngineTelemetryLogRequestObject) (GetEngineTelemetryLogResponseObject, error)

	// (POST /engines/telemetry/log)
	PostEngineTelemetryLog(ctx context.Context, request PostEngineTelemetryLogRequestObject) (PostEngineTelemetryLogResponseObject, error)

	// (GET /engines/telemetry/traces)
	GetEngineTelemetryTraces(ctx context.Context, request GetEngineTelemetryTracesRequestObject) (GetEngineTelemetryTracesResponseObject, error)

	// (POST /engines/telemetry/traces)
	PostEngineTelemetryTraces(ctx context.Context, request PostEngineTelemetryTracesRequestObject) (PostEngineTelemetryTracesResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetEngineConfig operation middleware
func (sh *strictHandler) GetEngineConfig(w http.ResponseWriter, r *http.Request) {
	var request GetEngineConfigRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEngineConfig(ctx, request.(GetEngineConfigRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEngineConfig")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEngineConfigResponseObject); ok {
		if err := validResponse.VisitGetEngineConfigResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEngineTelemetryLog operation middleware
func (sh *strictHandler) GetEngineTelemetryLog(w http.ResponseWriter, r *http.Request) {
	var request GetEngineTelemetryLogRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEngineTelemetryLog(ctx, request.(GetEngineTelemetryLogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEngineTelemetryLog")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEngineTelemetryLogResponseObject); ok {
		if err := validResponse.VisitGetEngineTelemetryLogResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEngineTelemetryLog operation middleware
func (sh *strictHandler) PostEngineTelemetryLog(w http.ResponseWriter, r *http.Request, params PostEngineTelemetryLogParams) {
	var request PostEngineTelemetryLogRequestObject

	request.Params = params

	var body PostEngineTelemetryLogJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEngineTelemetryLog(ctx, request.(PostEngineTelemetryLogRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEngineTelemetryLog")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEngineTelemetryLogResponseObject); ok {
		if err := validResponse.VisitPostEngineTelemetryLogResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetEngineTelemetryTraces operation middleware
func (sh *strictHandler) GetEngineTelemetryTraces(w http.ResponseWriter, r *http.Request) {
	var request GetEngineTelemetryTracesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetEngineTelemetryTraces(ctx, request.(GetEngineTelemetryTracesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetEngineTelemetryTraces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetEngineTelemetryTracesResponseObject); ok {
		if err := validResponse.VisitGetEngineTelemetryTracesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostEngineTelemetryTraces operation middleware
func (sh *strictHandler) PostEngineTelemetryTraces(w http.ResponseWriter, r *http.Request, params PostEngineTelemetryTracesParams) {
	var request PostEngineTelemetryTracesRequestObject

	request.Params = params

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostEngineTelemetryTraces(ctx, request.(PostEngineTelemetryTracesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostEngineTelemetryTraces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostEngineTelemetryTracesResponseObject); ok {
		if err := validResponse.VisitPostEngineTelemetryTracesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
